---

- name: Add Docker GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  become: yes

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes

- name: Add user to docker group
  user:
    name: "{{ system_user }}"
    groups: docker
    append: yes
  become: yes
  register: docker_group

- name: Reset connection to start a new session
  meta: reset_connection
  when: docker_group.changed

- name: Install Docker for Python
  pip:
    name: docker
    extra_args: --user